version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:4.8.7

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install --pure-lockfile --ignore-engines

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # Check syntax
      - run: find ~/repo/ -path ~/repo/node_modules -prune -o -name "*.js" -print0 | xargs -0 -n1 node -c
